version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: film_db
    container_name: film_db_container
    environment:
      HOST: db
      PORT: 5432
      DB: film_db
      DB_USER: film_db
      DB_PASSWORD: film_db
    networks:
      - film_net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.2
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: file_db
      POSTGRES_USER: file_db
      POSTGRES_PASSWORD: file_db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - film_net
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:

networks:
  film_net:
